name = "GradientSketching"
uuid = "a81232b9-fb8f-487c-b42c-5a1a812653cf"
authors = ["Albin Severinson <albin@severinson.org> and contributors"]
version = "0.1.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
